services:
  postgres:
    image: postgres:16
    container_name: rateio_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: rateio
      POSTGRES_PASSWORD: rateio123
      POSTGRES_DB: rateio_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: