/**
 * Chave normalizada da descrição no PDF → chave normalizada da coluna C do modelo Belle.
 */

export const BELLE_PDF_DESC_TO_TEMPLATE_KEY: Record<string, string> = {
  RECEITAS: "RECEITAS",
  DESPESAS: "DESPESAS",
  "RECEITAS DO MES - TOTAL GERAL": "TOTAL RECEITAS DO MES",
  "DESPESAS DO MES - TOTAL GERAL": "TOTAL DESPESAS DO MES",
  "RECEITAS MENSAIS - TOTAL GRUPO": "TOTAL",
  "RECEITAS DE COTAS - TOTAL GRUPO": "TOTAL",
  "RECEITAS FINANCEIRAS - TOTAL GRUPO": "TOTAL",
  "DESPESAS ORDINARIAS - TOTAL GRUPO": "TOTAL DESPESAS ORDINARIAS",
  "DESPESAS AGUA E ESGOTO - TOTAL GRUPO": "TOTAL DESPESAS AGUA E ESGOTO",
  "DESPESAS FUNDO DE MANUTENCAO - TOTAL GRUPO": "TOTAL DESPESAS FUNDO DE MANUTENCAO",
};
